### ISSUE TITLE
Connecting to host using ip fails but name works.

### ISSUE THREAD

**Issue by steffenix** [bitwalker/libcluster#129]
Using the https://hexdocs.pm/libcluster/Cluster.Strategy.Kubernetes.DNS.html#content strategy I get the ips using `:a` defaut option. But my node list remains empty.
In fact I can connect to the node using their name but not using their ip.

I wonder if this is an issue with erlang or Kubernetes

```
iex(app@app-7b77bc47b4-qtwlq)1> Node.list
[]
iex(app@app-7b77bc47b4-qtwlq)2> Node.connect(:"app@10.16.5.77")
false
iex(app@app-7b77bc47b4-qtwlq)3> Node.connect(:"app@10.16.4.175")
false
iex(app@app-7b77bc47b4-qtwlq)4> Node.connect(:"app@app-7b77bc47b4-qtwlq")
true
```

**Comment by steffenix** [comment]
What I ended up doing.

Add a env variable in the kubernetes config

```
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```


In the env.sh.eex

```
export RELEASE_DISTRIBUTION=name
export RELEASE_NODE=<%= @release.name %>@$POD_IP
```
