### ISSUE TITLE
Failed to connect using the Cluster.Strategy.Kubernetes strategy

### ISSUE THREAD

**Issue by vincent-lg** [bitwalker/libcluster#178]
### Steps to reproduce

- Configuration Used: in brief, a Kubernetes cluster with replicas that all run but do not connect automatically (they do manually).
- Strategy Used: `Cluster.Strategy.Kubernetes`.
- Errors/Incorrect Behaviour Encountered: `08:45:18.137 [error] [libcluster:default] request to kubernetes failed!: {:failed_connect, [{:to_address, {'kubernetes.default.svc.cluster.local', 443}}, {:inet, [:inet], :nxdomain}]}`

### Description of issue

- What are the expected results? Pods should connect automatically with one another.
- Is the documentation incorrect? You'll decide, I would guess no.

### Configuration

I'm running on WSL and have installed both Docker and Minikube locally.  I can build using Docker and run my release.  Minikube can deploy two replicas of my Docker image in two pods.  These pods do not connect, even after configuration libcluster.  If I manually connect them (using `Node.connect(:"full address")` ), things work and the connection is maintained.  Still, libcluster doesn't perceive my pods and connect them, it seems.

I tried to solve this issue and found [a similar issue](https://github.com/bitwalker/libcluster/issues/19), but adding `:ssl` and `:crypto` to my applications doesn't solve the error which might have been different.

A Kubernetes configuration is quite verbose, so here are the various files I've used:

```elixir
# ... Extracted from applicatoin.ex
  def start(_type, _args) do
    topologies = [
      default: [
        strategy: Cluster.Strategy.Kubernetes,
        config: [
          mode: :dns,
          kubernetes_node_basename: "myapp",
          kubernetes_selector: "app=myapp,tier=web",
          kubernetes_namespace: "default",
          polling_interval: 10_000
        ]
      ]
    ]

    children = [
      {Cluster.Supervisor, [topologies, [name: Myapp.ClusterSupervisor]]},
      # Start the Ecto repository
      Carte.Repo,
      # Start the Telemetry supervisor
      CarteWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Carte.PubSub},
      # Start the Endpoint (http/https)
      CarteWeb.Endpoint
      # Start a worker by calling: Carte.Worker.start_link(arg)
      # {Carte.Worker, arg}
    ]
    # ...
  end
```

```
# rel/env.sh.eex
# ...

export POD_A_RECORD=$(echo $POD_IP | sed 's/\./-/g')
export RELEASE_DISTRIBUTION=name
export RELEASE_NODE=myapp@${POD_A_RECORD}.${NAMESPACE}.pod.cluster.local
```

```
# myapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        tier: web
    spec:
      containers:
        - name: myapp
          image: carte:v10
          ports:
            - containerPort: 4000
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PHX_HOST
              value: "localhost"
            - name: SECRET_KEY_BASE
              value: "RLG+sdfZgQK7j0kNCTJtOxR0ws20ZvsA0Q45G2kY6vTJnnCNAWYkN6hd4QHleF5m"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "postgres"
            - name: PGDATABASE
              value: "carte_prod"
            - name: DB_HOSTNAME
              value: db
            - name: PGPORT
              value: "5432"
```

```
# myapp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  ports:
    - port: 8000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: myapp
  type: LoadBalancer
```

Because I encountered some libcluster errors about roles and permissions, I also added a role and role-binding:

```
# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: some-permissions
  namespace: default
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
```

```
# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: give-default-sa-some-permissions
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: some-permissions
  apiGroup: rbac.authorization.k8s.io
```

I might have made a mistake there, I found only a distant fix and I'm not sure I actually fixed the issue.  All I can say is, the error changed after applying these.

### Setup

* Operating system : Windows WSL (Ubuntu).
* Application: Elixir + bare Phoenix (Live).
* Elixir version: 1.13.4.
* OTP version: 25.0.2.
* Libcluster version: 3.3.1.

Thanks,

**Comment by oladipo** [comment]
Have you been able to resolve this one? I am also experiencing exactly the same thing.

**Comment by vincent-lg** [comment]
It seems I took a (very bad) shortcut: I had to setup a private service so that `libcluster` could find all the IPs in the cluster.  It was indicated in the documentation I was following, so no good excuse on my part, I'm afraid.  For further reference, here's the service I added to my cluster:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-dns
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: 4369
  selector:
    app: myapp
```

I had the funny impression my load balancer did just that.  But it didn't.  This is a headless service.

I'm not completely sure it's necessary but I followed another tutorial and used a slightly different topology as well.  It looks more simple:

```elixir
# lib/carte/application.ex
defmodule Carte.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    topologies = [
      default: [
        strategy: Cluster.Strategy.Kubernetes.DNS,
        config: [
          service: "myapp-dns",
          application_name: "myapp"
        ]
      ]
    ]

    children = [
      {Cluster.Supervisor, [topologies, [name: Myapp.ClusterSupervisor]]},
      # Start the Ecto repository
      Carte.Repo,
      # Start the Telemetry supervisor
      CarteWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Carte.PubSub},
      # Start the Endpoint (http/https)
      CarteWeb.Endpoint
      # Start a worker by calling: Carte.Worker.start_link(arg)
      # {Carte.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Carte.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    CarteWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end
```

The cluster strategy is different, though I'm not quite sure.  One key is the name of the Kubernetes service to be used though, since I was missing this configuration (and the service altogether).

For me, it did the trick.  I even could create a PostgreSQL service afterward.  Here's the blog post I used: https://medium.com/@groksrc/elixir-kubernetes-part-3-9bbd71c9c370 .

A last note: not being familiar with Kubernetes myself it took a great amount of time and reading and debugging.  And I realize, now that it's working, how much the system has changed but how much it has improved as well.  Phoenix can actually generate a Docker file for us which needs minimal adjustment (I don't think I actually changed it myself).  All we need is a way to have up-to-date information, but that's a broad topic.

Hope that helps,
