### ISSUE TITLE
Libcluster unable to connect when new deploy happens k8s

### ISSUE THREAD

**Issue by newton-peixoto** [bitwalker/libcluster#186]
Hello everyone, first of all thanks for this amazing tool! I'd like to understand what I'm missing to be able to deploy a new image of my application and it connects to the  already running  nodes. I`m able to accomplish that using the ``Elixir.Cluster.Strategy.LocalEpmd`` strategy but I want to do the same on a k8s system. 

### Steps to reproduce

```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-api-deployment
  namespace: default
spec:
  minReadySeconds: 20
  replicas: 5
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app: cluster-api
  template:
    metadata:
      labels:
        app: cluster-api
    spec:
      containers:
      - name: cluster-api
        image: cluster:8.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: SECRET_KEY_BASE
          value: "nnZYyX3y2NJP2Mf/vGFX9ilh4DtMwPdQ8CZYhd/pb83J/GXVUwFwfByRY1t2C49w"
        - name: PORT
          value: "4000"
        - name: ERLANG_COOKIE
          value: "secret"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["elixir"]
        args: [
          "--name", 
          "cluster@$(MY_POD_IP)", 
          "--cookie","$(ERLANG_COOKIE)", 
          "--no-halt", 
          "-S","mix",
          "run"
        ]
---
kind: Service
apiVersion: v1

metadata:
  name: cluster-api-service
  namespace: default
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: cluster-api
  ports:
      - name: http
        port: 4000
```

```
config :libcluster,
  topologies: [
    dns: [
      strategy: Elixir.Cluster.Strategy.Kubernetes.DNS,
        config: [
          service: "cluster-api-service",
          application_name: "cluster"
        ]
      ]
  ]
```

### Description of issue

I expect the new node with a new docker image (updated code) to connect to the previous running ones and stop getting the following message on my logs
```
[warning] [libcluster:dns] unable to connect to :
```
