### ISSUE TITLE
Headless k8 service instead of relying on K8 APIs

### ISSUE THREAD

**Issue by seivan** [bitwalker/libcluster#35]
One of the ways we solved this was creating a headless `Service` for all the `Deployments` or `Daemonset`  that should join the cluster.
That way when the application launches using the `<app@ip>` it can do a lookup agains the service name and get the addresses for the rest of the cluster to join. 

I am not sure, but my guess is (and correct me if I am wrong) using the Kubernetes API might break requirements for some people who don't want to expose those things on the pod/containers.

**Comment by bitwalker** [comment]
So far I haven't had any pushback on it, since permissions are pretty fine-grained, exposing the ability to list endpoints is pretty low-risk. That said, if there is an alternative method that I can either make part of the documentation, or support in the k8s strategy itself, I'm certainly open to that!

**Comment by seivan** [comment]
Yeah I am not so concerned over security more than I am over relying on an API that is often subject to change compared to a regular nslookup .

```
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: my-backend
  name: my-backend-list
  namespace: default
spec:
  clusterIP: None 
  ports:
    - port: 80
  selector:
    name: my-backend
```

This would you do a lookup via `:inet_res.getbyname('my-backend-list', :a)` and get all the nodes. 
I would *guess* this is less code than using the Kubernetes API directly. 
The less code (e.g working with the K8 API) the better, when you can rely on the internal DNS.
