### ISSUE TITLE
[libcluster:app_name] cannot query kubernetes (unauthorized): endpoints is forbidden: User  cannot list endpoints in the namespace "staging": Unknown user, User cannot list endpoints in the namespace

### ISSUE THREAD

**Issue by DinaWork** [bitwalker/libcluster#54]
I am running `kubernetes 1.9.4` on my cluster

I have two pods , `gate` which is trying to connect to `coolapp`

I am using `libcluster` to connect my nodes
I get the following error:
```
[libcluster:app_name] cannot query kubernetes (unauthorized): endpoints is forbidden: User "system:serviceaccount:staging:default" cannot list endpoints in the namespace "staging": Unknown user "system:serviceaccount:staging:default"
```

here is my config in **gate** under `config/prod`:
```
 config :libcluster,
 topologies: [
   app_name: [
     strategy: Cluster.Strategy.Kubernetes,
     config: [
       kubernetes_selector: "tier=backend",
       kubernetes_node_basename: System.get_env("MY_POD_NAMESPACE") || "${MY_POD_NAMESPACE}"]]]

```

here is my configuration:

**vm-args**
```
## Name of the node
-name ${MY_POD_NAMESPACE}@${MY_POD_IP}
## Cookie for distributed erlang
-setcookie ${ERLANG_COOKIE}
# Enable SMP automatically based on availability
-smp auto

```

**creating the secrets:**
```
kubectl create secret generic erlang-config --namespace staging --from-literal=erlang-cookie=xxxxxx
kubectl create configmap vm-config --namespace staging --from-file=vm.args

```
**gate/deployment.yaml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gate
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: gate
        tier: backend
    spec:
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      containers:
      - name: gate
        image: gcr.io/development/gate:0.1.7
        args:
          - foreground
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /beamconfig
        env:
        - name: MY_POD_NAMESPACE
          value: staging
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RELEASE_CONFIG_DIR
          value: /beamconfig
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang-config
              key: erlang-cookie
      volumes:
      - name: config-volume
        configMap:
          name: vm-config

```
**coolapp/deployment.yaml:**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coolapp
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: coolapp
        tier: backend
    spec:
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
     # volumes
      volumes:
      - name: config-volume
        configMap:
          name: vm-config
      containers:
      - name: coolapp
        image: gcr.io/development/coolapp:1.0.3
        volumeMounts:
        - name: secrets-volume
          mountPath: /secrets
          readOnly: true
        - name: config-volume
          mountPath: /beamconfig
        ports:
        - containerPort: 80
        args:
          - "foreground"
        env:
        - name: MY_POD_NAMESPACE
          value: staging
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPLACE_OS_VARS
          value: "true"
        - name: RELEASE_CONFIG_DIR
          value: /beamconfig
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang-config
              key: erlang-cookie
        # proxy_container
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
            "-instances=staging:us-central1:com-staging=tcp:5432",
            "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: cloudsql
            mountPath: /cloudsql
 

```

**Comment by tsupertramp** [comment]
Hey Ho @DinaWork ,

the problem you have is that RBAC is not configured properly.
https://kubernetes.io/docs/admin/authorization/rbac/

RBAC allows or in your case denies the access to kubernetes api.

You first need to create a servieaccout which has rights (role) through connecting a serviceaccount with a role (this is done by a rolebinding).

```---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-name
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: role-name
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rolebinding-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-name
subjects:
  - kind: ServiceAccount
    name: serviceaccount-name```

Furthermore your deployment needs to be configured to use this serviceaccount:
```
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: coolapp
        tier: backend
    spec:
      serviceAccountName: serviceaccount-name```

Greetings, Thomas

**Comment by DinaWork** [comment]
thanks!! that solved my issue

**Comment by sdia** [comment]
Hi @tsupertramp ,

I the same error message than the original question. I tried your suggestion now the error is gone, but I still cannot build a cluster. 

Note: I can connect to the pod and issue a ping, which manually connect the node and make a cluster.

Please find below my kubernetes config, is there anything I am missing ? Many thanks

Seydou


```
--- # https://github.com/bitwalker/libcluster/issues/54
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-service-account


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: myapp-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rolebinding-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myapp-role
subjects:
  - kind: ServiceAccount
    name: myapp-service-account


---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8000
      # Port to forward to inside the pod
      targetPort: 8000
      # Port accessible outside cluster
      nodePort: 32002
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp-service-account
      containers:
        - name: myapp
          image: sdia/abento:latest
          imagePullPolicy: Always
          env:
            - name: REPLACE_OS_VARS
              value: 'true'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8000
```
