### ISSUE TITLE
k8s: Clustering apps with different base names

### ISSUE THREAD

**Issue by vasu-dasari** [bitwalker/libcluster#63]
Say, I have three Elixir/Erlang services A(3 replicas), B(2 replicas) and C(2 replicas) in same namespace. And I would like to cluster A and B apps together and leave app C on its own. I do not think I can do this with existing codebase. Please correct me otherwise.

I can do a PR for this feature if it cannot be done currently.

**Comment by vasu-dasari** [comment]
Created a [PR](https://github.com/bitwalker/libcluster/pull/65/commits/53dec1acce390c93c74cb45c3901c810f7efd1cd) to address this. Please let me know what do you think of this?

**Comment by seivan** [comment]
Don't include `C` in the headless service, that way it won't be accessible for lookup. 
For the rest (`A`and `B`) make sure they got a shared selector they can use and investigate using the [DNS](https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes_dns.ex#L15-L23)  strategy instead 

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    deployment: web
  name: web-headless
  namespace: default
spec:
  clusterIP: None 
  ports:
    - port: 80
  selector:
    deployment: web
```
