### ISSUE TITLE
Unable to connect to nodes

### ISSUE THREAD

**Issue by pedromvieira** [bitwalker/libcluster#64]
I followed issue [54](https://github.com/bitwalker/libcluster/issues/54).
I have a minikube cluster with specific deployment, serviceaccount, role, etc.
And still unable to connect nodes.
Tried with hex and github versions.

```
k8s/deployment.yaml
kind: Deployment
metadata:
  name: phishx
  namespace: phishx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: phishx-app
        tier: phishx-tier
    spec:
      serviceAccountName: phishx-account
      containers:
        - name: phishx
          image: phishx/release:0.5.4
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          args: ["foreground"]
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets:
        - name: cloud.docker.com
```

```
config/prod.exs
config :libcluster,
  topologies: [
    k8s: [
      strategy: Cluster.Strategy.Kubernetes,
      config: [
        kubernetes_selector: "tier=phishx-tier",
        kubernetes_node_basename: "phishx"
      ]
    ]
]
```

```
kubectl get pods -o wide
NAME                      READY     STATUS    RESTARTS   AGE       IP           NODE
phishx-66b67bfb59-6jrmh   1/1       Running   0          4m        172.17.0.6   minikube
phishx-66b67bfb59-csrvd   1/1       Running   0          4m        172.17.0.4   minikube
phishx-66b67bfb59-rsg2v   1/1       Running   0          4m        172.17.0.5   minikube
```

```
kubectl logs -f phishx-66b67bfb59-6jrmh
18:55:32.111 [warn] [libcluster:k8s] unable to connect to :"phishx@172.17.0.4"
18:55:32.126 [warn] [libcluster:k8s] unable to connect to :"phishx@172.17.0.5"
18:55:32.129 [warn] [libcluster:k8s] unable to connect to :"phishx@172.17.0.6"
```
